service: import-service

plugins:
  - serverless-esbuild

custom:
  esbuild:
    platform: node
    target: node18
  queue_name: catalogItemsQueue

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource:
            - "arn:aws:s3:::shop-aws-task-5-container/*"
        - Effect: "Allow"
          Action:
            - "sqs:GetQueueUrl"
            - "sqs:SendMessage"
          Resource: "*"

functions:
  importProductsFile:
    handler: functions/importProductsFile.default
    events: 
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer: {
            arn: 'arn:aws:lambda:${self:provider.region}:060881416814:function:authorization-service-dev-basicAuthorizer',
            type: 'request'
          }
  importFileParser:
    handler: functions/importFileParser.default
    events:
      - s3:
          bucket: shop-aws-task-5-container
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true
    environment:
      queue: ${self:custom.queue_name}

resources:
  Resources:
    Unauthorized:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: "DEFAULT_4XX"
        RestApiId:
          Ref: "ApiGatewayRestApi"
